import { getPool } from '../store/postgres.js';
import { pendingEmailClaimKey } from './pendingEmailPolicy.js';

export type PendingEmailClaimInput = {
  userId: string;
  taskId: string;
  notificationType: string;
  notificationDate: string;
};

let tableReady: Promise<void> | null = null;

const CREATE_CLAIMS_SQL = `
  CREATE TABLE IF NOT EXISTS email_notification_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_key TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    notification_type TEXT NOT NULL,
    notification_date TEXT NOT NULL,
    status TEXT NOT NULL,
    sent_at TIMESTAMPTZ,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
`;

function ensureClaimsTable(): Promise<void> {
  if (!tableReady) {
    tableReady = getPool()
      .query(CREATE_CLAIMS_SQL)
      .then(() => undefined)
      .catch((error: unknown) => {
        tableReady = null;
        throw error;
      });
  }
  return tableReady;
}

/**
 * Insert-or-skip claim. Only the caller that receives `claimed` may send.
 * A unique claim_key blocks a second scheduler tick or a second backend instance.
 */
export async function claimPendingEmailSend(
  input: PendingEmailClaimInput
): Promise<'claimed' | 'duplicate'> {
  await ensureClaimsTable();
  const claimKey = pendingEmailClaimKey(input);
  const result = await getPool().query(
    `
      INSERT INTO email_notification_claims
        (claim_key, user_id, task_id, notification_type, notification_date, status, retry_count)
      VALUES ($1, $2, $3, $4, $5, 'SENDING', 0)
      ON CONFLICT (claim_key) DO NOTHING
      RETURNING id
    `,
    [claimKey, input.userId, input.taskId, input.notificationType, input.notificationDate]
  );
  return result.rows.length > 0 ? 'claimed' : 'duplicate';
}

export async function completePendingEmailClaim(
  input: PendingEmailClaimInput,
  status: 'SENT' | 'FAILED'
): Promise<void> {
  await ensureClaimsTable();
  const claimKey = pendingEmailClaimKey(input);
  await getPool().query(
    `
      UPDATE email_notification_claims
      SET
        status = $2,
        sent_at = CASE WHEN $2 = 'SENT' THEN NOW() ELSE sent_at END,
        retry_count = CASE WHEN $2 = 'FAILED' THEN retry_count + 1 ELSE retry_count END
      WHERE claim_key = $1
    `,
    [claimKey, status]
  );
}
